// Thin typed client over specs/assistant/api-contracts.md. The client never
// invents shapes (platform web.md): request bodies carry exactly the fields
// the contract names, responses are trusted as the wire types.
//
// `fetchFn` is the module's API seam — unit tests mock the API here, no live
// server needed (web.md Test Harness).

import type {
  AccountWire,
  Priority,
  RepeatFrequency,
  SessionReadWire,
  TaskView,
  TaskWire,
  TurnRequestBody,
  TurnResponseWire,
  UndoOutcomeWire,
} from '../types.ts'

export type FetchLike = (url: string, init?: RequestInit) => Promise<Response>

export type ApiResult<T> =
  | { kind: 'ok'; value: T }
  | {
      kind: 'http-error'
      status: number
      code: string
      message: string
      detail?: Record<string, unknown>
      /** full parsed body — 502 AI_ERROR / 500 APPLY_FAILED carry {error, turn} */
      body: unknown
    }
  | { kind: 'network'; error: unknown }

/**
 * `TASK_CREATE_FIELDS`, in full (api-contracts § `POST /tasks`).
 *
 * **Every member is optional but `title`, and that is a hazard rather than a
 * convenience** (`F-005 ## Impact §1`, fifteenth closed field list): a caller
 * that forgets a field gets **no compile error**, which is exactly how
 * `pushLocalTasks`'s replay literal silently dropped five of them. The
 * enumeration is written out here rather than grown ad hoc so the replay can be
 * checked against it by reading one screen.
 */
export interface TaskCreateBody {
  /** Optional client-generated uuid (api-contracts, supporting endpoints): the
   * offline local path creates the task under a real id and replays the create
   * on reconnect — there is no temporary-id mapping. A colliding id answers
   * `409 TASK_ID_EXISTS`, which a client replaying its own create reads as its
   * already-synced ack. */
  id?: string
  title: string
  note?: string | null
  due_at?: string | null
  /** AC-13 — **a create supplying this keeps it.** The offline replay carries it
   * so a task created offline on Today never needs re-deriving and the *one row,
   * three answers* case cannot arise for it (ADR-010). */
  due_all_day?: boolean | null
  /** NEW in F-005 — `POST` refused this field before. */
  reminder_at?: string | null
  priority?: Priority | null
  /** `today` is still rejected (ADR-009). */
  status?: string
  /** NEW in F-005 — this is what makes a step creatable in ONE call (AC-14).
   * POST-then-PATCH opens a window in which the step exists at an undefined
   * position and AC-3 renders it to every other client. */
  parent_id?: string | null
  /** NEW in F-005 — **a create supplying it keeps it**; a create supplying none
   * is appended last, positioned by the server (ADR-015, AC-14). */
  step_order?: number | null
  repeat_frequency?: RepeatFrequency | null
  repeat_interval?: number | null
  repeat_weekdays?: string | null
  repeat_month_days?: string | null
  repeat_until?: string | null
  repeat_count?: number | null
}

/**
 * `TASK_PATCH_FIELDS`, in full (api-contracts § `PATCH /tasks/{id}`) — the
 * create list **minus `id` and `parent_id`, plus `step_order`**.
 *
 * `parent_id` is deliberately **not** patchable: a step does not change parents
 * this phase, and re-parenting is a gesture no AC describes and no control
 * offers. `reminder_shown_at`, `series_live`, `series_id`,
 * `completed_by_parent` and `deleted_at` are not patchable either — each has
 * exactly one writer, named where it is defined.
 */
export interface TaskPatchBody {
  title?: string
  note?: string | null
  due_at?: string | null
  due_all_day?: boolean | null
  reminder_at?: string | null
  priority?: Priority | null
  status?: string
  /** AC-15 / ADR-015 — how a move is made. One write, one row. */
  step_order?: number | null
  repeat_frequency?: RepeatFrequency | null
  repeat_interval?: number | null
  repeat_weekdays?: string | null
  repeat_month_days?: string | null
  repeat_until?: string | null
  repeat_count?: number | null
}

/**
 * **The multi-row response rule** (api-contracts § The multi-row response rule;
 * `F-005` AC-26, AC-2).
 *
 * Any write that changes more than one row returns every row it changed. The
 * receiver half is not optional: without it a successor generated by a hand tick
 * appears **nowhere** until an unrelated refresh, and `F-005 AC-39` is
 * vacuously true on the platform it was created for.
 */
export interface TaskWriteResult {
  /** the row the request addressed. */
  task: TaskView
  /** every OTHER row this write changed; may be absent or `[]`. The addressed
   * row is never repeated here. */
  changed?: TaskView[]
  /** rows HARD-removed by this write (AC-28's successor removal, deliberately
   * not a soft delete). Omitted when empty. */
  removed?: string[]
  /** ADR-015 — the pre-write value of each field the write actually changed;
   * `{}` when the write was a no-op. **The single source for the reorder undo's
   * prior position** — no new record is owed. */
  prior?: Record<string, unknown>
  /** `POST /tasks/{id}/restore` — `false` on the stated no-op (AC-41). */
  restored?: boolean
  /** `POST /tasks/{id}/reminder-ack` — `false` on a done or deleted row. */
  acknowledged?: boolean
}

/** `POST /tasks/{id}/repeat-preview` — a dry run of the same server code, so
 * the disclosed date is by construction the date that will be written (AC-22,
 * AC-23, AC-25). A client-side preview would be a second implementation of the
 * alignment, the month-day clamp and the exclusivity rules — L-004's shape. */
export interface RepeatPreviewWire {
  due_at: string | null
  due_all_day: boolean
  /** AC-22 created a due where there was none. */
  created: boolean
  /** AC-23 moved the due forward onto the rule. */
  moved: boolean
  /** what a commit would refuse; `[]` if it would succeed. */
  refusals: { code: string; field: string | null; message: string }[]
}

export class AssistantApi {
  private readonly base: string
  private readonly userId: string
  private readonly fetchFn: FetchLike

  constructor(opts: { baseUrl?: string; userId: string; fetchFn?: FetchLike }) {
    this.base = opts.baseUrl ?? ''
    this.userId = opts.userId
    this.fetchFn = opts.fetchFn ?? ((url, init) => globalThis.fetch(url, init))
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<ApiResult<T>> {
    let res: Response
    try {
      res = await this.fetchFn(`${this.base}${path}`, {
        method,
        headers: {
          'content-type': 'application/json',
          'X-User-Id': this.userId,
        },
        body: body === undefined ? undefined : JSON.stringify(body),
      })
    } catch (error) {
      return { kind: 'network', error }
    }
    let parsed: unknown = null
    try {
      parsed = await res.json()
    } catch {
      parsed = null
    }
    if (res.ok) return { kind: 'ok', value: parsed as T }
    const err = (parsed as { error?: { code?: string; message?: string; detail?: Record<string, unknown> } } | null)?.error
    return {
      kind: 'http-error',
      status: res.status,
      code: err?.code ?? 'UNKNOWN',
      message: err?.message ?? `HTTP ${res.status}`,
      detail: err?.detail,
      body: parsed,
    }
  }

  /** POST /assistant/turn — one conversation turn; answers are normal turns. */
  postTurn(body: TurnRequestBody): Promise<ApiResult<TurnResponseWire>> {
    return this.request('POST', '/assistant/turn', body)
  }

  /** GET /assistant/session — resume, or the clean-start boundary (AC-28). */
  getSession(): Promise<ApiResult<SessionReadWire>> {
    return this.request('GET', '/assistant/session')
  }

  /** POST /assistant/session/close */
  closeSession(sessionId: string): Promise<ApiResult<unknown>> {
    return this.request('POST', '/assistant/session/close', {
      session_id: sessionId,
      reason: 'user_closed',
    })
  }

  /** POST /assistant/turn/{turn_id}/undo (AC-5..8) */
  undoTurn(turnId: string, via: 'tap' | 'voice'): Promise<ApiResult<UndoOutcomeWire>> {
    return this.request('POST', `/assistant/turn/${turnId}/undo`, { via })
  }

  // ---- manual path (AC-18) — /tasks only, never /assistant/* ----

  listTasks(): Promise<ApiResult<{ tasks: TaskView[] }>> {
    return this.request('GET', '/tasks')
  }

  createTask(body: TaskCreateBody): Promise<ApiResult<TaskWriteResult>> {
    return this.request('POST', '/tasks', body)
  }

  patchTask(id: string, body: TaskPatchBody): Promise<ApiResult<TaskWriteResult>> {
    return this.request('PATCH', `/tasks/${id}`, body)
  }

  /**
   * `scope` is AC-30's two things one control must name: `occurrence` (this row
   * and its steps) or `series` (every UNFINISHED occurrence and their steps,
   * leaving every completed one — those are a record of work that was actually
   * done, not rubbish).
   */
  deleteTask(id: string, scope: 'occurrence' | 'series' = 'occurrence'): Promise<ApiResult<TaskWriteResult>> {
    const q = scope === 'series' ? '?scope=series' : ''
    return this.request('DELETE', `/tasks/${id}${q}`)
  }

  /** `POST /tasks/{id}/restore` (AC-41). The write path four ACs assert on and
   * nothing in the system could perform before F-005. Restoring is not creating:
   * the row keeps its id, `step_order`, `series_id` and `created_at`. */
  restoreTask(id: string): Promise<ApiResult<TaskWriteResult>> {
    return this.request('POST', `/tasks/${id}/restore`, {})
  }

  /** `POST /tasks/{id}/reminder-ack` (AC-38). The instant is required so that
   * acknowledging an old reminder cannot retire a reminder that moved
   * underneath — that answers `409 REMINDER_MOVED` and writes nothing. */
  ackReminder(id: string, reminderAt: string): Promise<ApiResult<TaskWriteResult>> {
    return this.request('POST', `/tasks/${id}/reminder-ack`, { reminder_at: reminderAt })
  }

  /** `POST /tasks/{id}/repeat-preview` (AC-22, AC-23, AC-25). Writes nothing,
   * makes zero AI calls, and is the same code the commit runs. */
  repeatPreview(id: string, body: TaskPatchBody): Promise<ApiResult<RepeatPreviewWire>> {
    return this.request('POST', `/tasks/${id}/repeat-preview`, body)
  }

  /** `GET /account` (ADR-010) — the ONE source every date computation reads. */
  getAccount(): Promise<ApiResult<AccountWire>> {
    return this.request('GET', '/account')
  }

  /** `PATCH /account` — the only way to change an already-set zone. */
  patchAccount(timezone: string): Promise<ApiResult<AccountWire>> {
    return this.request('PATCH', '/account', { timezone })
  }
}
