// F-005 — the shared controller's half, under node.
//
// Everything asserted here lives in `src/assistant/_shared/`, **which the mobile
// client compiles**, so every case is a case about both clients:
//
//   - **AC-2 / AC-26's receiver clause.** The sender obligation is the server's;
//     without the receiver, AC-39 is *vacuously true on the platform it was created
//     for* — the successor is never drawn on the phone, so no mutation of the repeat
//     mark can turn the mobile case red.
//   - **AC-2's third state, scoped by row PROVENANCE.** The clause four lenses
//     caught, and the one most likely to be got wrong: unscoped, it removes working
//     behaviour, and QA writes from the spec, so the test would have asserted the
//     refusal and the regression would have shipped green.
//   - **AC-47's notice**, whose mechanism must observe *every* write to a field.
//   - **AC-14 / AC-13's replay literal**, which produces no compile error when a
//     field is missed.
//   - **AC-44's one clock**, driven by the one seam.
//   - **AC-38's opening installer**, and **AC-43's single-slot offer**.

import { describe, expect, it } from 'vitest'
import { harness, task, todayTask, T0 } from './_helpers.ts'
import { noticeFor, retryableFields } from '../../_shared/model/notices.ts'
import { installClock } from '../../_shared/model/clock.ts'
import { formatDue } from '../../_shared/model/format.ts'
import { inCollection, startOfTodayIso } from '../../_shared/model/tasks.ts'
import { isStep, remainingSteps, seriesLive } from '../../_shared/model/task-fields.ts'
import type { TaskView, TaskWire } from '../../_shared/types.ts'

const settle = async (): Promise<void> => {
  await Promise.resolve()
  await new Promise((r) => setTimeout(r, 0))
  await Promise.resolve()
}

/**
 * A controller whose session read answers the contract's *no open session* shape.
 *
 * `init()` walks the session route, and the fake's catch-all `200 {}` is not a
 * `SessionReadWire` — so a suite that drives `init()` has to say what the session
 * read returns, or it is asserting against a response the server cannot send.
 */
function scripted(opts: { online?: boolean } = {}) {
  const h = harness(opts)
  h.server.always('GET /assistant/session', 200, { session: null, boundary: null })
  return h
}

const find = (h: ReturnType<typeof harness>, id: string): TaskView | undefined =>
  h.controller.state.tasks.find((t) => t.id === id)

// ---------------------------------------------------------------------------
// AC-2 / AC-26 — the client applies what a write returns
// ---------------------------------------------------------------------------

describe('AC-2 / AC-26 — the receiver clause', () => {
  it('applies the addressed row AND every member of `changed` — the successor is drawn with no refresh', async () => {
    // AC-26's own case, and the reason the receiver half exists: *"a successor
    // generated by a hand tick appears NOWHERE until some unrelated event
    // refreshes, at which point a row the user never created materialises with no
    // gesture attached."*
    const occurrence = todayTask({ id: 'occ-1', title: 'Water the plants', series_live: true })
    const successor = task({
      id: 'occ-2',
      title: 'Water the plants',
      due_at: '2026-08-26T00:00:00.000Z',
      series_id: 'series-1',
      series_live: true,
    })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [occurrence] }
    h.server.always('PATCH /tasks/:id', 200, {
      task: { ...occurrence, status: 'done' },
      changed: [successor],
    })

    await h.controller.toggleTask('occ-1')

    expect(find(h, 'occ-1')?.status).toBe('done')
    expect(find(h, 'occ-2'), 'the successor the write returned').toBeDefined()
    // …and it arrived from the RESPONSE, not from a blind re-read. The rows were
    // already in hand, which is why api-contracts rejects the `GET` alternative.
    expect(h.server.calls.filter((c) => c.method === 'GET' && c.path === '/tasks')).toHaveLength(0)
    // AC-39's mark has something to be about on this client now — which is the
    // whole of what "vacuously true" meant before.
    expect(seriesLive(find(h, 'occ-2') as TaskWire)).toBe(true)
  })

  it('drops every id in `removed` — AC-28’s successor removal is a HARD removal', async () => {
    // *"Removes the successor" is a hard removal, not a soft delete* (architect L1):
    // a soft-removed successor is a row AC-41 can restore, producing the second open
    // occurrence the whole recurrence section rests on not having.
    const done = todayTask({ id: 'occ-1', status: 'done', series_live: true })
    const successor = task({ id: 'occ-2', series_id: 'series-1', series_live: true })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [done, successor] }
    h.server.always('PATCH /tasks/:id', 200, {
      task: { ...done, status: 'inbox' },
      changed: [],
      removed: ['occ-2'],
    })

    await h.controller.toggleTask('occ-1')

    expect(find(h, 'occ-1')?.status).toBe('inbox')
    expect(find(h, 'occ-2'), 'the removed successor is gone from client state').toBeUndefined()
  })

  it('applies AC-19’s cascade — steps ticked by their parent arrive in `changed`', async () => {
    const parent = todayTask({ id: 'p1', title: 'Pack' })
    const s1 = task({ id: 's1', title: 'passport', parent_id: 'p1', step_order: 1024 })
    const s2 = task({ id: 's2', title: 'charger', parent_id: 'p1', step_order: 2048 })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [parent, s1, s2] }
    h.server.always('PATCH /tasks/:id', 200, {
      task: { ...parent, status: 'done' },
      changed: [
        { ...s1, status: 'done', completed_by_parent: true },
        { ...s2, status: 'done', completed_by_parent: true },
      ],
    })

    await h.controller.toggleTask('p1')

    expect(find(h, 's1')?.status).toBe('done')
    expect(find(h, 's2')?.status).toBe('done')
    // AC-35 — and the steps are still in NO collection, on either client, which is
    // *"the cascade neither corrupts the list nor leaves a step visible"*.
    const now = new Date(T0)
    for (const c of ['inbox', 'today', 'upcoming', 'done'] as const) {
      expect(inCollection(find(h, 's1') as TaskWire, c, now), `s1 in ${c}`).toBe(false)
    }
    // …and the parent's own remaining count is a different number about a
    // different set (AC-17), which is now zero rather than absent.
    expect(remainingSteps(h.controller.state.tasks, 'p1')).toBe(0)
  })

  it('tolerates a 2xx with no `task` rather than throwing — a server bug is not a dead surface', async () => {
    const row = todayTask({ id: 't1' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('PATCH /tasks/:id', 200, {})
    await expect(h.controller.toggleTask('t1')).resolves.toBeUndefined()
    // The optimistic value stands, which is what the code did before the receiver
    // clause existed — so a stub answering `{}` behaves exactly as it used to.
    expect(find(h, 't1')?.status).toBe('done')
  })
})

// ---------------------------------------------------------------------------
// AC-2's third state — scoped by row provenance
// ---------------------------------------------------------------------------

describe('AC-2 — the offline state is scoped by row PROVENANCE', () => {
  it('a SERVER-OWNED row is refused: nothing sent, the value not applied, the reason stated', async () => {
    const row = todayTask({ id: 'srv-1', title: 'Call the bank' })
    const h = harness({ online: false })
    h.controller.state = { ...h.controller.state, tasks: [row], offline: true }

    await h.controller.editTask('srv-1', 'Call the bank back')

    // **Never sent.** Not queued, not stored, not replayed — *"there is no NEW
    // queue, no NEW durable store and no replay of edits"*.
    expect(h.server.calls.filter((c) => c.method === 'PATCH')).toHaveLength(0)
    expect(h.stores.localTasks()).toEqual([])
    // The row shows what the server holds. AC-2's mobile-tier outcome: *"the row
    // shows the value the server holds and the failure is stated — never a row that
    // vanishes and returns at the next refresh"*.
    expect(find(h, 'srv-1')?.title).toBe('Call the bank')
    // The value is not lost either: it is in the notice, with a user-invoked retry.
    const n = noticeFor(h.controller.state.notices, 'srv-1')
    expect(n?.fields.map((f) => [f.field, f.value, f.reason])).toEqual([
      ['title', 'Call the bank back', 'offline-refused'],
    ])
    expect(retryableFields(n!).map((f) => f.field)).toEqual(['title'])
    // …and the reason given is an OFFLINE refusal, announced under 4.1.3.
    expect(h.controller.state.announce?.text).toContain("offline")
  })

  it('a LOCALLY-CREATED row is kept and replayed, exactly as it is today', async () => {
    // **The clause four lenses caught.** The shipped guard has three disjuncts and
    // the unscoped rule inverted the behaviour on the first: create a task offline
    // under F-001 AC-25, then be unable to fix a typo in it. `persistLocal()`
    // genuinely saves the edit and `pushLocalTasks` genuinely replays it — that
    // store and that replay ship today, and this AC neither builds nor widens them.
    const h = scripted({ online: false })
    await h.controller.init()
    await h.controller.addTask('typo')
    const id = h.controller.state.tasks[0]?.id as string
    expect(find(h, id)?.local).toBe(true)

    await h.controller.editTask(id, 'fixed')

    expect(find(h, id)?.title, 'the edit is APPLIED, not refused').toBe('fixed')
    expect(h.stores.localTasks().map((t) => t.title), 'and it is durably saved').toEqual(['fixed'])
    // No notice: nothing failed and nothing was refused.
    expect(noticeFor(h.controller.state.notices, id)).toBeNull()
  })

  it('the first disjunct fires WHILE ONLINE, and the refusal never claims otherwise', async () => {
    // *"An unsynced local row whose replay failed stays `local: true` with
    // connectivity restored. Scoping the refusal by provenance removes that case
    // entirely: the offline refusal is stated only when the app is actually offline,
    // so the reason given is never one the user can disprove by looking at their
    // connection."*
    const h = scripted({ online: false })
    await h.controller.init()
    await h.controller.addTask('made offline')
    const id = h.controller.state.tasks[0]?.id as string
    // Back online, replay not done — the row is still `local: true`.
    h.controller.state = { ...h.controller.state, offline: false }
    expect(find(h, id)?.local).toBe(true)

    await h.controller.editTask(id, 'renamed while online')

    expect(find(h, id)?.title).toBe('renamed while online')
    expect(
      h.controller.state.announce?.text ?? '',
      'no "you are offline" for a row edited while online',
    ).not.toContain('offline')
  })

  it('a server-owned DELETE offline is refused, the row stays, and NO undo offer is made', async () => {
    // AC-43's mobile bullet: *"Offline it cannot run at all: `removeTask` never
    // reaches the server and AC-41's restore is a server call, so the delete is
    // AC-2's offline refusal and no offer is made."*
    const row = todayTask({ id: 'srv-1', title: 'Pay the bill' })
    const h = harness({ online: false })
    h.controller.state = { ...h.controller.state, tasks: [row], offline: true }

    await h.controller.removeTask('srv-1')

    expect(h.server.calls.filter((c) => c.method === 'DELETE')).toHaveLength(0)
    expect(find(h, 'srv-1'), 'the row stays').toBeDefined()
    expect(h.controller.state.undoOffer, 'an offer would point at a row nothing deleted').toBeNull()
  })
})

// ---------------------------------------------------------------------------
// AC-2's second state, and AC-42's *for a delete that happened*
// ---------------------------------------------------------------------------

describe('AC-2 / AC-42 — a write that FAILED', () => {
  it('a failed field write reverts the row to what the server holds and keeps the value in a notice', async () => {
    const row = todayTask({ id: 't1', title: 'Original' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'boom' } })

    await h.controller.editTask('t1', 'Typed but not saved')

    expect(find(h, 't1')?.title, 'the row shows what the store holds').toBe('Original')
    const n = noticeFor(h.controller.state.notices, 't1')
    expect(n?.fields[0]).toMatchObject({ field: 'title', value: 'Typed but not saved', reason: 'failed' })
    expect(n?.ended).toBeNull()
  })

  it('a FAILED delete brings the row back, states it, and is NOT an undo case', async () => {
    // dev-backend F7: `removeTask` never inspected its result, so on a failed
    // `DELETE` the row was already gone locally with nothing on the server to
    // reverse — an undo would call AC-41's restore on a live row and tell the user
    // something was restored that was never deleted. **The offer follows the
    // write's RESULT.**
    const row = todayTask({ id: 't1', title: 'Still here' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('DELETE /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'boom' } })

    await h.controller.removeTask('t1')

    expect(find(h, 't1'), 'the row comes back').toBeDefined()
    expect(h.controller.state.undoOffer).toBeNull()
    expect(h.controller.state.announce?.text).toContain("wasn't deleted")
  })

  it('a write that fails BECAUSE THE TASK IS GONE produces no notice at all (AC-4)', async () => {
    // *"There is nothing to retry and nothing to write into: a notice offering retry
    // on a deleted task is either dead or a resurrection, and AC-4 forbids both.
    // AC-4's terminal state remains the whole of that case."*
    const row = todayTask({ id: 't1', title: 'Original' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('PATCH /tasks/:id', 404, { error: { code: 'NOT_FOUND', message: 'gone' } })

    await h.controller.editTask('t1', 'Typed')

    expect(noticeFor(h.controller.state.notices, 't1')).toBeNull()
    expect(h.controller.state.announce?.text).toContain('is gone')
  })

  it('concurrent failures report ONCE, naming the fields — not one announcement per field', async () => {
    // AC-2, design D4: *"One polite announcement per failure technically satisfies
    // 4.1.3 while making the surface unusable for exactly the users AC-16 and AC-33
    // exist for."*
    const row = todayTask({ id: 't1', title: 'Original', note: null })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'boom' } })

    await h.controller.writeField('t1', { title: 'A' })
    await h.controller.writeField('t1', { note: 'B' })

    // ONE notice for the task, carrying both fields (AC-47's aggregation).
    expect(h.controller.state.notices).toHaveLength(1)
    const n = noticeFor(h.controller.state.notices, 't1')
    expect(n?.fields.map((f) => f.field).sort()).toEqual(['note', 'title'])
    // …and ONE sentence naming both.
    const said = h.controller.state.announce?.text ?? ''
    expect(said).toContain('name')
    expect(said).toContain('note')
  })
})

// ---------------------------------------------------------------------------
// AC-47 — supersede, and the four writers the mechanism must observe
// ---------------------------------------------------------------------------

describe('AC-47 — the notice, and who supersedes it', () => {
  it('a later write by ANYONE supersedes it: the notice STANDS, reports, and loses its retry', async () => {
    // *"A later successful write supersedes the notice whoever made it — the user's
    // retry or an assistant turn — and a supersede by a turn is announced rather
    // than silent."* Both halves matter: ending it silently discards a typed value
    // without saying so; keeping the retry is a control that overwrites the newer
    // stored value with the stale failed one.
    const row = todayTask({ id: 't1', title: 'Original' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'boom' } })
    await h.controller.writeField('t1', { title: 'Typed' })
    expect(retryableFields(noticeFor(h.controller.state.notices, 't1')!)).toHaveLength(1)

    // An assistant turn renames the same field — arriving through the refresh path,
    // which is one of the four writers the mechanism has to observe.
    h.server.always('GET /tasks', 200, { tasks: [{ ...row, title: 'Renamed by the assistant' }] })
    await h.controller.refreshTasks()

    const n = noticeFor(h.controller.state.notices, 't1')
    expect(n, 'the notice STANDS — supersession is not an ender').not.toBeNull()
    expect(n?.fields[0]?.superseded).toBe(true)
    expect(n?.fields[0]?.value, 'and it still carries what the user typed').toBe('Typed')
    expect(n?.fields[0]?.storedNow, 'and says which value the field holds now').toBe(
      'Renamed by the assistant',
    )
    // **No retry.** The resurrection door AC-4 and AC-47 close everywhere else.
    expect(retryableFields(n!)).toHaveLength(0)
    // …and a retry invoked anyway is a no-op rather than a stale write.
    await h.controller.retryNotice('t1', 'title')
    expect(find(h, 't1')?.title).toBe('Renamed by the assistant')
  })

  it('a retry that SUCCEEDS is the one path that removes the field', async () => {
    const row = todayTask({ id: 't1', title: 'Original' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.once('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'boom' } })
    await h.controller.writeField('t1', { title: 'Typed' })
    expect(noticeFor(h.controller.state.notices, 't1')).not.toBeNull()

    h.server.always('PATCH /tasks/:id', 200, { task: { ...row, title: 'Typed' } })
    await h.controller.retryNotice('t1', 'title')

    expect(noticeFor(h.controller.state.notices, 't1')).toBeNull()
    expect(find(h, 't1')?.title).toBe('Typed')
  })

  it('the task being DELETED ends the notice as a report — value legible, no retry', async () => {
    // AC-4 / AC-47, tester W9, design D20: reachable from an ordinary sequence —
    // fail a write, close the detail, say *"delete that"*.
    const row = todayTask({ id: 't1', title: 'Original' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.once('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'boom' } })
    await h.controller.writeField('t1', { title: 'Typed' })

    h.server.always('DELETE /tasks/:id', 200, { task: { ...row, deleted_at: T0 } })
    await h.controller.removeTask('t1')

    const n = noticeFor(h.controller.state.notices, 't1')
    expect(n?.ended).toBe('task-deleted')
    expect(n?.fields[0]?.value, 'the value is still legible').toBe('Typed')
    expect(retryableFields(n!), 'and there is no retry').toHaveLength(0)
  })

  it('a rename reaches the notice, because after the row is gone it holds the only copy of the name', async () => {
    const row = todayTask({ id: 't1', title: 'Original' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.once('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'x' } })
    await h.controller.writeField('t1', { note: 'a note that failed' })
    expect(noticeFor(h.controller.state.notices, 't1')?.taskTitle).toBe('Original')

    h.server.always('GET /tasks', 200, { tasks: [{ ...row, title: 'Renamed' }] })
    await h.controller.refreshTasks()

    expect(noticeFor(h.controller.state.notices, 't1')?.taskTitle).toBe('Renamed')
  })

  it('a single-row response says NOTHING about other tasks, and ends none of their notices', async () => {
    // The trap in `reconcileNotices`: ending a notice on *absence from this response*
    // would end every notice on every single-row write. Only KNOWN deletion ends one.
    const a = todayTask({ id: 'a', title: 'A' })
    const b = todayTask({ id: 'b', title: 'B' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [a, b] }
    h.server.once('PATCH /tasks/:id', 500, { error: { code: 'INTERNAL', message: 'x' } })
    await h.controller.writeField('a', { title: 'typed on A' })

    h.server.always('PATCH /tasks/:id', 200, { task: { ...b, title: 'B2' } })
    await h.controller.writeField('b', { title: 'B2' })

    const n = noticeFor(h.controller.state.notices, 'a')
    expect(n?.ended, 'A’s notice is untouched by a write about B').toBeNull()
    expect(retryableFields(n!)).toHaveLength(1)
  })

  it('the user dismissing it is the only user ender', () => {
    const h = scripted()
    h.controller.state = {
      ...h.controller.state,
      notices: [
        {
          taskId: 't1',
          taskTitle: 'X',
          fields: [{ field: 'title', value: 'v', baseline: 'o', reason: 'failed', superseded: false }],
          ended: null,
          at: T0,
        },
      ],
    }
    h.controller.dismissNotice('t1')
    expect(h.controller.state.notices).toEqual([])
  })
})

// ---------------------------------------------------------------------------
// AC-43 — the hand-action undo
// ---------------------------------------------------------------------------

describe('AC-43 — the hand-action undo offer', () => {
  it('a delete that HAPPENED offers it, and AC-41’s restore puts the row back', async () => {
    const row = todayTask({ id: 't1', title: 'Order the cake' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('DELETE /tasks/:id', 200, { task: { ...row, deleted_at: T0 } })

    await h.controller.removeTask('t1')

    expect(h.controller.state.undoOffer?.action).toEqual({
      kind: 'delete-task',
      taskId: 't1',
      title: 'Order the cake',
    })
    expect(h.controller.state.undoOffer?.used).toBe(false)
    expect(find(h, 't1')).toBeUndefined()

    h.server.always('POST /tasks/:id/restore', 200, { task: row, changed: [], restored: true })
    await h.controller.undoLastAction()

    expect(find(h, 't1'), 'the row is back, with its own id').toBeDefined()
    // The offer becomes CN-UNDONE rather than vanishing: the row is what reports
    // that the reversal happened.
    expect(h.controller.state.undoOffer?.used).toBe(true)
  })

  it('does NOT stack — a second undoable action replaces the first, and the replaced action stays done', async () => {
    const a = todayTask({ id: 'a', title: 'A' })
    const b = todayTask({ id: 'b', title: 'B' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [a, b] }
    h.server.always('DELETE /tasks/:id', 200, { task: { ...a, deleted_at: T0 } })

    await h.controller.removeTask('a')
    await h.controller.removeTask('b')

    expect(h.controller.state.undoOffer?.action).toMatchObject({ taskId: 'b' })
    // A is still deleted. This is one of the two mechanisms by which a deleted row
    // becomes permanently unrecoverable with the row still on disk — named in
    // **OQ13**, which asks the owner about the depth of recovery.
    expect(find(h, 'a')).toBeUndefined()
  })

  it('is not usable twice, and a `Put back` that never reached the server leaves the offer standing', async () => {
    const row = todayTask({ id: 't1', title: 'X' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('DELETE /tasks/:id', 200, { task: { ...row, deleted_at: T0 } })
    await h.controller.removeTask('t1')

    h.server.once('POST /tasks/:id/restore', 500, { error: { code: 'INTERNAL', message: 'x' } })
    await h.controller.undoLastAction()
    expect(h.controller.state.undoOffer?.used, 'nothing was put back').toBe(false)
    expect(h.controller.state.announce?.text).toContain("couldn't be undone")

    h.server.always('POST /tasks/:id/restore', 200, { task: row, restored: true })
    await h.controller.undoLastAction()
    expect(find(h, 't1')).toBeDefined()
  })

  it('AC-41’s stated no-op is stated — not a 404 and not a 409', async () => {
    const row = todayTask({ id: 't1', title: 'X' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [row] }
    h.server.always('DELETE /tasks/:id', 200, { task: { ...row, deleted_at: T0 } })
    await h.controller.removeTask('t1')
    h.server.always('POST /tasks/:id/restore', 200, { task: row, restored: false })

    await h.controller.undoLastAction()

    // *"A double-tap is ordinary on an undo that is one action away wherever the
    // user is, and a silent no-op is indistinguishable from a refusal unless one of
    // them is stated."*
    expect(h.controller.state.announce?.text).toBe('That was already back.')
  })

  it('a step delete offers it and a series delete offers its own class', async () => {
    const parent = todayTask({ id: 'p', title: 'Pack' })
    const s1 = task({ id: 's1', title: 'passport', parent_id: 'p', step_order: 1024 })
    const series = todayTask({ id: 'r1', title: 'Water', series_live: true, series_id: 'S' })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [parent, s1, series] }
    h.server.always('DELETE /tasks/:id', 200, { task: { ...s1, deleted_at: T0 } })

    await h.controller.removeTask('s1')
    expect(h.controller.state.undoOffer?.action).toEqual({
      kind: 'delete-step',
      taskId: 's1',
      title: 'passport',
      parentId: 'p',
    })

    h.server.always('DELETE /tasks/:id', 200, { task: { ...series, deleted_at: T0 } })
    await h.controller.removeSeries('r1')
    expect(h.controller.state.undoOffer?.action).toMatchObject({ kind: 'delete-series', taskId: 'r1' })
    // AC-30's two scopes are two requests, and the scope is on the wire.
    expect(h.server.calls.some((c) => c.method === 'DELETE' && c.path.includes('scope=series'))).toBe(
      true,
    )
  })

  it('a reorder offers it and replays `prior.step_order` through the SAME write path', async () => {
    // ADR-015: *"No new record, one source, and the undo's write path is the move's
    // write path"* — L-005's remedy rather than a second door onto ordering.
    const s1 = task({ id: 's1', title: 'one', parent_id: 'p', step_order: 1024 })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [s1] }
    h.server.always('PATCH /tasks/:id', 200, {
      task: { ...s1, step_order: 3072 },
      prior: { step_order: 1024 },
    })

    await h.controller.moveStep('s1', 3072)
    expect(h.controller.state.undoOffer?.action).toEqual({
      kind: 'move-step',
      taskId: 's1',
      title: 'one',
      priorStepOrder: 1024,
    })

    h.server.always('PATCH /tasks/:id', 200, { task: { ...s1, step_order: 1024 }, prior: {} })
    await h.controller.undoLastAction()
    const patches = h.server.calls.filter((c) => c.method === 'PATCH')
    expect(patches.at(-1)?.body).toEqual({ step_order: 1024 })
  })

  it('a drop where the step already was creates NO entry — the server’s empty `prior` is the observable', async () => {
    const s1 = task({ id: 's1', title: 'one', parent_id: 'p', step_order: 1024 })
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [s1] }
    h.server.always('PATCH /tasks/:id', 200, { task: s1, prior: {} })

    await h.controller.moveStep('s1', 1024)

    expect(h.controller.state.undoOffer, 'no offer for something that did not happen').toBeNull()
  })
})

// ---------------------------------------------------------------------------
// AC-14 / AC-13 — the replay literal
// ---------------------------------------------------------------------------

describe('AC-14 / AC-13 — the offline create replay carries the whole field set', () => {
  it('an offline-created STEP replays with its parent and its position — not as a top-level task', async () => {
    // *"Read the wrong way an offline-created step replays with `parent_id` dropped
    // and returns as an ordinary top-level task, in every collection and every
    // count, which is what AC-35 exists to prevent."*
    const h = scripted({ online: false })
    await h.controller.init()
    // The offline create path is F-001 AC-25's; a step made offline is the row that
    // reaches the replay carrying structure, so it is built through the store the
    // replay actually reads.
    const local = task({
      id: 'local-step',
      title: 'passport',
      parent_id: 'parent-1',
      step_order: 2048,
      due_all_day: true,
      note: 'in the drawer',
      reminder_at: '2026-08-20T09:00:00.000Z',
      priority: 'high',
    })
    h.stores.saveLocalTasks([{ ...local, local: true }])
    // The replay ends with a read-back — *"the server is the authority now"* — so
    // the read has to answer the contract's shape rather than the fake's catch-all.
    h.server.always('GET /tasks', 200, { tasks: [] })

    h.controller.setOnline(true)
    await settle()

    const posted = h.server.calls.filter((c) => c.method === 'POST' && c.path === '/tasks')
    expect(posted).toHaveLength(1)
    expect(posted[0]?.body).toMatchObject({
      id: 'local-step',
      parent_id: 'parent-1',
      step_order: 2048,
      due_all_day: true,
      note: 'in the drawer',
      reminder_at: '2026-08-20T09:00:00.000Z',
      priority: 'high',
    })
  })

  it('a task created offline on TODAY replays as all-day — never a bare local midnight', async () => {
    // AC-13's third writer (dev-mobile F5), and ADR-010's answer: the offline create
    // *"computes in the device zone and stores the answer rather than deferring
    // it"*. Without the flag the row renders as **"12:00 AM"**.
    const h = scripted({ online: false })
    await h.controller.init()
    await h.controller.addTask('bought offline', 'today')
    const created = h.controller.state.tasks[0] as TaskWire
    expect(created.due_at).toBe(startOfTodayIso(new Date(T0)))
    expect(created.due_all_day, 'the flag is stored at creation, not deferred').toBe(true)

    h.server.always('GET /tasks', 200, { tasks: [] })
    h.controller.setOnline(true)
    await settle()

    const posted = h.server.calls.filter((c) => c.method === 'POST' && c.path === '/tasks')
    expect(posted[0]?.body).toMatchObject({ due_all_day: true })
  })

  it('and the row renders with NO clock time — the defect AC-13 forbids, on the landing collection', () => {
    const now = new Date(T0)
    const midnight = startOfTodayIso(now)
    // What shipped: a clock time for a time nobody picked.
    expect(formatDue(midnight, now)).toBe('12:00 AM')
    // What AC-13 requires, once the flag travels with the instant.
    expect(formatDue(midnight, now, { allDay: true })).toBe('Today')
  })
})

// ---------------------------------------------------------------------------
// AC-44 — one clock, driven by the one seam
// ---------------------------------------------------------------------------

describe('AC-44 — one clock seam per side', () => {
  it('`setClock` holds the controller’s instant, and the model defaults follow it', () => {
    const h = scripted()
    const before = installClock(h.controller.clockProvider())
    try {
      h.controller.setClock({ at: '2027-03-14T09:26:00.000Z', zone: 'Europe/Berlin' })
      // The controller's own reader…
      expect(h.controller.nowDate().toISOString()).toBe('2027-03-14T09:26:00.000Z')
      // …and the eight defaulted `now` parameters, which is the half that could not
      // be reached before: a default is what makes a missed injection silently
      // wall-clock instead of a type error.
      expect(startOfTodayIso()).toBe(
        new Date(2027, 2, 14, 0, 0, 0, 0).toISOString(),
      )
      // The zone is the computation zone (ADR-010), not what this client reports.
      expect(h.controller.zone()).toBe('Europe/Berlin')
      // Held: it does not advance on its own.
      expect(h.controller.nowDate().toISOString()).toBe('2027-03-14T09:26:00.000Z')
    } finally {
      installClock(before)
    }
  })

  it('the provider delegates rather than holding a clock of its own — no second seam', () => {
    const h = scripted()
    const p = h.controller.clockProvider()
    h.controller.setClock({ at: '2030-01-01T00:00:00.000Z' })
    expect(p.nowDate().toISOString()).toBe('2030-01-01T00:00:00.000Z')
    h.controller.setClock({ at: '2031-01-01T00:00:00.000Z' })
    expect(p.nowDate().toISOString(), 'the provider follows the seam it delegates to').toBe(
      '2031-01-01T00:00:00.000Z',
    )
  })

  it('the account zone is read from GET /account and cached durably — never the device zone', async () => {
    const h = scripted()
    h.server.always('GET /account', 200, {
      user_id: 'user-1',
      timezone: 'Asia/Ho_Chi_Minh',
      timezone_source: 'first-report',
      timezone_set_at: T0,
      timezone_last_report: 'Asia/Ho_Chi_Minh',
      timezone_last_report_at: T0,
    })
    await h.controller.loadAccount()
    expect(h.controller.zone()).toBe('Asia/Ho_Chi_Minh')
    expect(h.stores.accountTimezone(), 'cached, so an offline cold open has a zone').toBe(
      'Asia/Ho_Chi_Minh',
    )
  })
})

// ---------------------------------------------------------------------------
// AC-38 — the opening installer
// ---------------------------------------------------------------------------

describe('AC-38 — a passed reminder is surfaced on open', () => {
  const passed = (over: Partial<TaskWire> = {}): TaskWire =>
    task({
      id: 'r1',
      title: 'Ring the dentist',
      reminder_at: '2026-08-15T09:00:00.000Z',
      reminder_shown_at: null,
      ...over,
    })

  it('one installer, and every reminder whose instant has passed and is unacknowledged is surfaced', () => {
    const h = scripted()
    h.controller.state = {
      ...h.controller.state,
      tasks: [
        passed({ id: 'old', reminder_at: '2026-08-10T09:00:00.000Z' }),
        passed({ id: 'newer', reminder_at: '2026-08-15T09:00:00.000Z' }),
        // future — not passed
        passed({ id: 'future', reminder_at: '2026-09-01T09:00:00.000Z' }),
        // acknowledged — a STORED fact, so it does not reappear on this launch, on
        // the next device, or after a reload
        passed({ id: 'acked', reminder_shown_at: T0 }),
        // done and deleted are not surfaced
        passed({ id: 'done', status: 'done' }),
        passed({ id: 'gone', deleted_at: T0 }),
      ],
    }

    h.controller.openingSync()

    // **N passed reminders are ONE surfacing, ordered oldest first** (tester W7,
    // product P3): a user returning after two weeks meets the whole set at once.
    expect(h.controller.state.reminders.map((r) => r.taskId)).toEqual(['old', 'newer'])
    expect(h.controller.state.announce?.text).toBe('2 reminders have passed.')
  })

  it('RENDERING is not resolution — reopening still surfaces an unacknowledged reminder', () => {
    // product P1, design D16: *"a user who opens the app, is interrupted and closes
    // it has spent their only delivery — on every device, permanently — while the
    // task is still undone."* The negative case is what makes this assertable, and
    // it is constructible because *"do not acknowledge"* is now a precondition
    // rather than an open gesture set.
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [passed()] }
    h.controller.openingSync()
    expect(h.controller.state.reminders).toHaveLength(1)
    // open, DO NOT acknowledge, reopen
    h.controller.openingSync()
    expect(h.controller.state.reminders, 'still there').toHaveLength(1)
    expect(h.server.calls.filter((c) => c.path.includes('reminder-ack'))).toHaveLength(0)
  })

  it('acknowledging is per-reminder and sends the INSTANT, so a moved reminder cannot be retired', async () => {
    const h = scripted()
    h.controller.state = {
      ...h.controller.state,
      tasks: [passed({ id: 'a' }), passed({ id: 'b', reminder_at: '2026-08-16T09:00:00.000Z' })],
    }
    h.controller.openingSync()
    h.server.always('POST /tasks/:id/reminder-ack', 200, {
      task: passed({ id: 'a', reminder_shown_at: T0 }),
      acknowledged: true,
    })

    await h.controller.acknowledgeReminder('a')

    // **Only what the user acknowledges is marked**: ten surfaced together of which
    // three were acted on do not silently retire the other seven. **No bulk
    // dismissal.**
    expect(h.controller.state.reminders.map((r) => r.taskId)).toEqual(['b'])
    const ack = h.server.calls.find((c) => c.path.includes('reminder-ack'))
    expect(ack?.body).toEqual({ reminder_at: '2026-08-15T09:00:00.000Z' })
  })

  it('offline, an acknowledgement is NOT recorded and the reminder re-surfaces at the next open', async () => {
    // The owner's correction of 2026-08-19: revision 3 said the acknowledgement *"is
    // recorded when connectivity returns"*, and that is the one mechanism the
    // owner's own answer forbids by name — **queue-and-replay for one field is
    // queue-and-replay**, arriving through a side door.
    const h = harness({ online: false })
    h.controller.state = { ...h.controller.state, tasks: [passed()], offline: true }
    h.controller.openingSync()

    await h.controller.acknowledgeReminder('r1')

    expect(h.server.calls.filter((c) => c.path.includes('reminder-ack'))).toHaveLength(0)
    expect(h.controller.state.announce?.text).toContain('come back next time')
    // Nothing durable changed, so the next open surfaces it again.
    h.controller.openingSync()
    expect(h.controller.state.reminders).toHaveLength(1)
  })

  it('a 409 REMINDER_MOVED puts it back rather than retiring one the server did not mark', async () => {
    const h = scripted()
    h.controller.state = { ...h.controller.state, tasks: [passed()] }
    h.controller.openingSync()
    h.server.always('POST /tasks/:id/reminder-ack', 409, {
      error: { code: 'REMINDER_MOVED', message: 'moved' },
    })

    await h.controller.acknowledgeReminder('r1')

    expect(h.controller.state.reminders, 'a reminder wrongly retired is not recoverable').toHaveLength(1)
  })
})

// ---------------------------------------------------------------------------
// AC-35 — a step is in no collection, no count, and is not drawn
// ---------------------------------------------------------------------------

describe('AC-35 — the one gate that reaches both clients', () => {
  it('a step is in NO collection, open or done — the gate sits before the done gate', () => {
    const now = new Date(T0)
    const openStep = task({ id: 's', parent_id: 'p', step_order: 1024 }) as TaskWire
    const doneStep = task({ id: 's2', parent_id: 'p', step_order: 2048, status: 'done' }) as TaskWire
    expect(isStep(openStep)).toBe(true)
    for (const c of ['inbox', 'today', 'upcoming', 'done'] as const) {
      expect(inCollection(openStep, c, now), `open step in ${c}`).toBe(false)
      // The done case is a real difference and not ordering taste: a done step must
      // be in Done no more than an open one is in Today, or AC-19's cascade puts
      // eight rows the user has never seen into a collection as top-level rows.
      expect(inCollection(doneStep, c, now), `done step in ${c}`).toBe(false)
    }
  })

  it('AC-17’s count is a different number about a different set — never a collection count', () => {
    const tasks = [
      todayTask({ id: 'p', title: 'Pack' }),
      task({ id: 's1', parent_id: 'p', step_order: 1024 }),
      task({ id: 's2', parent_id: 'p', step_order: 2048, status: 'done' }),
      task({ id: 's3', parent_id: 'p', step_order: 3072 }),
    ]
    expect(remainingSteps(tasks, 'p')).toBe(2)
    // A task with no steps shows nothing — the AC's own negative half.
    expect(remainingSteps(tasks, 's1')).toBe(0)
  })
})
